

export const blogItems = [
  {
    id: 1,
    title: "Farm Fresh to Your Doorstep: How We Deliver Pure Dairy Daily",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur",
    image: '/images/blog1.jpg',
    author: "Admin",
    date: "Oct 30, 2025",
    tags: ["Butter", "Ghee", "Cheese", "Organic"],
    content: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
      "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
      "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
    ],
    quote:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
    extraImage: '/images/blog1.jpg',
  },
  {
    id: 2,
    title: "Spread the Joy: Why Farm Butter Tastes Better",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur",
    image: '/images/blog2.png',
    author: "Admin",
    date: "Oct 22, 2025",
    tags: ["Milk", "Fresh", "Pasture"],
    content: [
      "Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.",
      "Curabitur non nulla sit amet nisl tempus convallis quis ac lectus.",
      "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi.",
    ],
    quote: "Freshness begins in the field and finishes in your glass.",
    extraImage: '/images/blog1.jpg',
  },
  {
    id: 3,
    title: "Refreshing Dairy Drinks: Lassi, Buttermilk & Flavored Milk Delights",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur",
    image: '/images/blog3.jpg',
    author: "Admin",
    date: "Oct 12, 2025",
    tags: ["Community", "Farm", "People"],
    content: [
      "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.",
      "Donec rutrum congue leo eget malesuada.",
      "Nulla quis lorem ut libero malesuada feugiat.",
    ],
    quote: "Good food starts with great people.",
    extraImage: '/images/blog1.jpg',
  },
  {
    id: 4,
    title: "Pure Milk, Pure Joy: What Makes Our Dairy Ice Cream Special",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur",
    image: '/images/blog4.jpg',
    author: "Admin",
    date: "Oct 5, 2025",
    tags: ["Organic", "Sustainability"],
    content: [
      "Curabitur aliquet quam id dui posuere blandit.",
      "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.",
      "Pellentesque in ipsum id orci porta dapibus.",
    ],
    quote: "Healthy soil, happy cows, better milk.",
    extraImage: '/images/blog1.jpg',
  },
  {
    id: 5,
    title: "Meet Our Farmers: The Heart of Our Dairy Family",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur",
    image: '/images/blog5.jpg',
    author: "Admin",
    date: "Oct 5, 2025",
    tags: ["Organic", "Sustainability"],
    content: [
      "Curabitur aliquet quam id dui posuere blandit.",
      "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.",
      "Pellentesque in ipsum id orci porta dapibus.",
    ],
    quote: "Healthy soil, happy cows, better milk.",
    extraImage: '/images/blog1.jpg',
  },
  {
    id: 6,
    title: "Farm-Fresh Curd: A Bowl Full of Good Health",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur",
    image: '/images/blog6.jpg',
    author: "Admin",
    date: "Oct 5, 2025",
    tags: ["Organic", "Sustainability"],
    content: [
      "Curabitur aliquet quam id dui posuere blandit.",
      "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.",
      "Pellentesque in ipsum id orci porta dapibus.",
    ],
    quote: "Healthy soil, happy cows, better milk.",
    extraImage: '/images/blog1.jpg',
  },
  {
    id:7,
    title: "Healthy Morning Starts with a Glass of Farm Fresh Milk",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur",
    image: '/images/blog7.jpg',
    author: "Admin",
    date: "Oct 5, 2025",
    tags: ["Organic", "Sustainability"],
    content: [
      "Curabitur aliquet quam id dui posuere blandit.",
      "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.",
      "Pellentesque in ipsum id orci porta dapibus.",
    ],
    quote: "Healthy soil, happy cows, better milk.",
    extraImage: '/images/blog1.jpg',
  },
  {
    id: 8,
    title: "5 Delicious Ways to Use Desi Ghee in Everyday Cooking",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur",
    image: '/images/blog8.jpg',
    author: "Admin",
    date: "Oct 5, 2025",
    tags: ["Organic", "Sustainability"],
    content: [
      "Curabitur aliquet quam id dui posuere blandit.",
      "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.",
      "Pellentesque in ipsum id orci porta dapibus.",
    ],
    quote: "Healthy soil, happy cows, better milk.",
    extraImage: '/images/blog1.jpg',
  },
  {
    id: 9,
    title: "A2 Milk: The Natural Choice for Better Digestion",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur",
    image: '/images/blog9.jpg',
    author: "Admin",
    date: "Oct 5, 2025",
    tags: ["Organic", "Sustainability"],
    content: [
      "Curabitur aliquet quam id dui posuere blandit.",
      "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.",
      "Pellentesque in ipsum id orci porta dapibus.",
    ],
    quote: "Healthy soil, happy cows, better milk.",
    extraImage: '/images/blog1.jpg',
  },
  {
    id: 10,
    title: "Farm-Fresh Paneer: Purity You Can Taste",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur",
    image: '/images/blog10.jpg',
    author: "Admin",
    date: "Oct 5, 2025",
    tags: ["Organic", "Sustainability"],
    content: [
      "Curabitur aliquet quam id dui posuere blandit.",
      "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.",
      "Pellentesque in ipsum id orci porta dapibus.",
    ],
    quote: "Healthy soil, happy cows, better milk.",
    extraImage: '/images/blog1.jpg',
  },
  {
    id: 11,
    title: "Pure Milk, Pure Joy: What Makes Our Dairy Ice Cream Special",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod. Lorem ipsum dolor sit amet, consectetur",
    image: '/images/blog1.jpg',
    author: "Admin",
    date: "Oct 5, 2025",
    tags: ["Organic", "Sustainability"],
    content: [
      "Curabitur aliquet quam id dui posuere blandit.",
      "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.",
      "Pellentesque in ipsum id orci porta dapibus.",
    ],
    quote: "Healthy soil, happy cows, better milk.",
    extraImage: '/images/blog1.jpg',
  },
];

export default blogItems;